### ISSUE TITLE
Add ostruct to gemspec?

### ISSUE THREAD

**Issue by chrisdebruin** [main-branch/process_executer#65]
Getting this warning: /versions/3.3.5/lib/ruby/3.3.0/ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.

Could you add ostruct to gemspec?

**Comment by jcouball** [comment]
The fix for this issue is part of v1.1.1 of this gem which has been published to rubygems.org.

**Comment by chrisdebruin** [comment]
@jcouball great thanks
