### ISSUE TITLE
NameError: uninitialized constant Forwardable

### ISSUE THREAD

**Issue by achamo** [main-branch/process_executer#71]
Hello,

With the latest update, I got this error. The latest release removed `require forwardable` somewhere while there is still at least one reference in `status.rb`

> NameError: uninitialized constant Forwardable
> 
>     ::Object.const_get(n)
>             ^^^^^^^^^^
> /Users/xx/.gem/bundler/ruby-3.1.6/gems/process_executer-1.1.1/lib/process_executer/status.rb:11:in `<class:Status>'
> /Users/xx/.gem/bundler/ruby-3.1.6/gems/process_executer-1.1.1/lib/process_executer/status.rb:10:in `<module:ProcessExecuter>'
> /Users/xx/.gem/bundler/ruby-3.1.6/gems/process_executer-1.1.1/lib/process_executer/status.rb:5:in `<top (required)>'

**Comment by jcouball** [comment]
Thank you for the report!

This has been addressed in process_executer-1.1.2
